# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: "Build and deploy ASP.Net Core app to Azure Web App: bookstore-api-eifert"
on:
  push:
    branches:
      - Mission13_Eifert
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Build with dotnet
        run: dotnet build backend/Mission11_Eifert/Mission11_Eifert/Mission11_Eifert.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish backend/Mission11_Eifert/Mission11_Eifert/Mission11_Eifert.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Copy database to publish folder
        run: cp backend/Mission11_Eifert/Mission11_Eifert/Data/Bookstore.sqlite ${{env.DOTNET_ROOT}}/myapp/Bookstore.sqlite

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "bookstore-api-eifert"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{env.DOTNET_ROOT}}/myapp
